#!/usr/bin/env python3
"""Bundle the 9 onboarding SVGs into a self-contained Figma plugin (code.js).

Figma plugins can't read local files, so we inline each SVG string. Run this
after _generate.py whenever the mockups change:
    python3 build.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(HERE)  # ../  (the mockups dir)

ORDER = [
    "0-download", "1-welcome", "2-microphone", "3-screen-recording",
    "4-accessibility", "5-automation", "6-calendar", "7-reminders", "8-finish",
]
LABELS = {
    "0-download": "0 · Download / Install",
    "1-welcome": "1 · Welcome",
    "2-microphone": "2 · Microphone + Speech",
    "3-screen-recording": "3 · Screen Recording",
    "4-accessibility": "4 · Accessibility",
    "5-automation": "5 · Automation",
    "6-calendar": "6 · Calendar (optional)",
    "7-reminders": "7 · Reminders (optional)",
    "8-finish": "8 · All set",
}

screens = []
for name in ORDER:
    with open(os.path.join(SRC, name + ".svg")) as f:
        screens.append({"name": name, "label": LABELS[name], "svg": f.read()})

code = """// AUTO-GENERATED by build.py — Perch Onboarding Builder.
// Creates one page with all onboarding screens as native, editable frames.
const SCREENS = %s;

(async () => {
  // New page so we never clobber existing work.
  const page = figma.createPage();
  page.name = "Perch Onboarding";
  await figma.setCurrentPageAsync(page);

  const FW = 400, FH = 600, GAP = 64, LABEL_H = 28;
  const made = [];

  for (let i = 0; i < SCREENS.length; i++) {
    const s = SCREENS[i];
    const node = figma.createNodeFromSvg(s.svg); // FrameNode
    node.name = s.name;
    node.x = i * (FW + GAP);
    node.y = LABEL_H + 16;
    page.appendChild(node);

    const label = figma.createText();
    await figma.loadFontAsync({ family: "Inter", style: "Bold" });
    label.fontName = { family: "Inter", style: "Bold" };
    label.characters = s.label;
    label.fontSize = 16;
    label.x = i * (FW + GAP);
    label.y = 0;
    label.fills = [{ type: "SOLID", color: { r: 0.85, g: 0.85, b: 0.88 } }];
    page.appendChild(label);

    made.push(node, label);
  }

  // Connector arrows between consecutive screens.
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  figma.currentPage.selection = made;
  figma.viewport.scrollAndZoomIntoView(made);
  figma.closePlugin("Built " + SCREENS.length + " onboarding screens on the 'Perch Onboarding' page.");
})();
""" % json.dumps(screens, ensure_ascii=False)

with open(os.path.join(HERE, "code.js"), "w") as f:
    f.write(code)
print("wrote", os.path.join(HERE, "code.js"), "with", len(screens), "screens")
