#!/usr/bin/env python3
"""Bundle the v2 onboarding SVGs into a self-contained Figma plugin (code.js).

Figma plugins can't read local files, so we inline each SVG string. Run this
after _generate_v2.py whenever the mockups change:
    python3 build.py

Then in Figma: Plugins -> Development -> Import plugin from manifest... -> pick
this folder's manifest.json, and run "Perch Onboarding v2 Builder". It creates a
new "Onboarding v2 — Refined" page with all screens as native, editable frames.
This path uses NO Figma MCP calls, so it is not affected by seat/plan rate limits.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(HERE)  # ../  (the v2 mockups dir)

ORDER = [
    "1-welcome", "2-microphone", "3-music", "4-calendar", "5-finish",
    "jit-permission",
]
LABELS = {
    "1-welcome": "1 · Welcome",
    "2-microphone": "2 · Microphone",
    "3-music": "3 · Music",
    "4-calendar": "4 · Calendar",
    "5-finish": "5 · You're all set",
    "jit-permission": "Just-in-time (Screen · Accessibility · Automation · Reminders)",
}

screens = []
for name in ORDER:
    with open(os.path.join(SRC, name + ".svg")) as f:
        screens.append({"name": name, "label": LABELS[name], "svg": f.read()})

code = """// AUTO-GENERATED by build.py — Perch Onboarding v2 Builder.
// Creates one page with all v2 onboarding screens as native, editable frames.
const SCREENS = %s;

(async () => {
  // New page so we never clobber existing work (e.g. the v1 import).
  const page = figma.createPage();
  page.name = "Onboarding v2 — Refined";
  await figma.setCurrentPageAsync(page);

  const FW = 400, FH = 600, GAP = 64, LABEL_H = 28;
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });
  const made = [];

  for (let i = 0; i < SCREENS.length; i++) {
    const s = SCREENS[i];
    const node = figma.createNodeFromSvg(s.svg); // FrameNode
    node.name = s.name;
    node.x = i * (FW + GAP);
    node.y = LABEL_H + 16;
    page.appendChild(node);

    const label = figma.createText();
    label.fontName = { family: "Inter", style: "Bold" };
    label.characters = s.label;
    label.fontSize = 16;
    label.x = i * (FW + GAP);
    label.y = 0;
    label.fills = [{ type: "SOLID", color: { r: 0.85, g: 0.85, b: 0.88 } }];
    page.appendChild(label);

    made.push(node, label);
  }

  figma.currentPage.selection = made;
  figma.viewport.scrollAndZoomIntoView(made);
  figma.closePlugin("Built " + SCREENS.length + " v2 onboarding screens on the 'Onboarding v2 — Refined' page.");
})();
""" % json.dumps(screens, ensure_ascii=False)

with open(os.path.join(HERE, "code.js"), "w") as f:
    f.write(code)
print("wrote", os.path.join(HERE, "code.js"), "with", len(screens), "screens")
